apiVersion: v1
kind: Pod
metadata:
  labels:
    run: loadgenertor
  name: loadgenertor
  selfLink: /api/v1/namespaces/default/pods/loadgenertor
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do wget -o - -q http://10.236.55.26:80; done
    image: eilinge/busybox:latest
    imagePullPolicy: IfNotPresent
    name: loadgenertor
