apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubia
  namespace: default
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/kubia
  uid: 85301f19-4812-4923-a566-c50c63a6fbaa
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubia
  targetCPUUtilizationPercentage: 80
